// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr_70ikozR9gPHZgOTb1iWxUlD-5fPwc8',
    appId: '1:581889039000:web:4a9961cd5b5e80116d4eed',
    messagingSenderId: '581889039000',
    projectId: 'proyecto1-70717',
    authDomain: 'proyecto1-70717.firebaseapp.com',
    storageBucket: 'proyecto1-70717.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl7-yUtvaISXZYHnXwlYBzEtu8XY9zuwI',
    appId: '1:581889039000:android:f14d3bb88e9453b86d4eed',
    messagingSenderId: '581889039000',
    projectId: 'proyecto1-70717',
    storageBucket: 'proyecto1-70717.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGgZNZ-J48pqtVnYUoxRXbde3Ht_QTh30',
    appId: '1:581889039000:ios:fe078bcb123033e16d4eed',
    messagingSenderId: '581889039000',
    projectId: 'proyecto1-70717',
    storageBucket: 'proyecto1-70717.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGgZNZ-J48pqtVnYUoxRXbde3Ht_QTh30',
    appId: '1:581889039000:ios:fe078bcb123033e16d4eed',
    messagingSenderId: '581889039000',
    projectId: 'proyecto1-70717',
    storageBucket: 'proyecto1-70717.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr_70ikozR9gPHZgOTb1iWxUlD-5fPwc8',
    appId: '1:581889039000:web:b89944328b9218eb6d4eed',
    messagingSenderId: '581889039000',
    projectId: 'proyecto1-70717',
    authDomain: 'proyecto1-70717.firebaseapp.com',
    storageBucket: 'proyecto1-70717.firebasestorage.app',
  );
}
